site_name: Apunts ED
site_description: Apunts del m貌dul Entorns de Desenvolupament 1DAW
theme: 
  name: 'material'
  language: 'ca'
  icon:
    repo: 'fontawesome/brands/github'
  palette:
    primary: purple
    scheme: default
    primary: "indigo"
    accent: "indigo"
  toggle:
        icon: material/weather-sunny
        name: "Canvia a mode clar"
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.copy        # bot贸 copiar codi
    - content.tabs.link
    - search.highlight  
    - content.action.print  # bot贸 imprimir

extra:
  print_page:
    print_button: true
    label: " Descarregar PDF"
    
plugins:
  - search
  - pdf-export

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details        # admonitions plegables
  - pymdownx.highlight:     # numeraci贸 l铆nies + copy button
      anchor_linenums: true
  - pymdownx.tabbed

nav:
  - Inici: index.md
  - UD1 Desenvolupament de programari : ud1-desenvolupament.md
  - UD2  Introducci贸 a Git: ud2-introduccio-git.md
  - UD3 Diagrama de classes UML: ud3-diagrama-classes.md
  - UD4 Git avan莽at: ud4-git-avancat.md
  - UD5 Prova de programari: ud5-prova-programari.md
  - UD6 Diagrames UML: ud6-diagrames-uml.md

extra_css:
  - css/styles.css